# Site settings
title: Sam Feng's Site
email: sfeng.oicr@gmail.com
description: >
  Practice personal website generating utilizing Jekyll, GitHub pages and MERN stack.
baseurl: "/samfeng279.github.io"
url: "https://samfeng279.github.io"
twitter_username:
github_username:  samfeng279

permalink: pretty

collections:
  _collection:
    output: true
    permalink: /collection/:title.html

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
# kramdown:
#  input: GFM
markdown: kramdown

plug-ins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock