# Site settings
title: Sam Feng's Site
description: >
  Hello and welcome! I'm a BME in my third year at UWaterloo.
baseurl: "/samfeng279.github.io"
url: "https://samfeng279.github.io"
twitter_username:
github_username:  samfeng279

permalink: pretty

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']

markdown: kramdown

keep_files: [assets]
exclude:
  - Gemfile
  - Gemfile.lock